apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: wlan-testing-deployment-autoscaler
spec:
  scaleTargetRef:
    name: wlan-testing-small-deployment
  minReplicas: 1
  maxReplicas: 3
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "24h"
