apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: wlan-testing-deployment-autoscaler
spec:
  scaleTargetRef:
    name: wlan-testing-small-deployment
  minReplicas: 0
  maxReplicas: 10
  scaleUpTriggers:
  - githubEvent: {}
    duration: "24h"
