apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: wlan-testing-small-deployment
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      repository: Telecominfraproject/wlan-testing
      imagePullPolicy: IfNotPresent
      env: []
      labels:
      - self-hosted
      - small
      resources:
        limits:
          cpu: "500m"
          memory: "500Mi"
        requests:
          cpu: "500m"
          memory: "500Mi"
      dockerdContainerResources:
        limits:
          cpu: "500m"
          memory: "500Mi"
        requests:
          cpu: "500m"
          memory: "500Mi"
