repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

environments:
  azure:
    values:
    - domain: tip.4c74356b41.com
    - storageClass: default
  amazon:
    values:
    - domain: tip.4c74356b41.com
    - storageClass: gp2

releases:
# core setup
- name: prometheus-operator
  namespace: monitoring
  chart: stable/prometheus-operator
  labels:
    app: prometheus-operator
    role: setup
  set:
  - name: prometheusOperator.manageCrds
    value: true
  - name: prometheusOperator.createCustomResource
    value: false
- name: fluentd
  namespace: monitoring
  chart: stable/fluentd
  labels:
    app: fluentd
    role: setup
  set:
  - name: output.host
    value: elasticsearch-client.monitoring.svc.cluster.local
- name: elasticsearch
  namespace: monitoring
  chart: stable/elasticsearch
  labels:
    app: elasticsearch
    role: setup
- name: prometheus-postgres-exporter
  namespace: monitoring
  chart: stable/prometheus-postgres-exporter
  labels:
    app: postgress-exporter
    role: setup
  set:
  - name: config.datasource.host
    value: "tip-postgresql.tip.svc.cluster.local"
  - name: config.datasource.password
    value: "cG9zdGdyZXMxMjM: "

# cloud sdk
- name: tip
  namespace: tip
  chart: tip-wlan
  labels:
    app: cloudsdk
    role: payload
  values:
  - tip-wlan/resources/environments/dev.yaml
  - wlan-cloud-graphql-gw:
      env:
        portalsvc: graphql.{{ .Environment.Values.domain }}
      ingress:
        hosts:
        - host: graphql.{{ .Environment.Values.domain }}
          paths:
          - "/"
  - wlan-cloud-static-portal:
      ingress:
        hosts:
        - host: portal.{{ .Environment.Values.domain }}
          paths:
          - "/"
  - nginx-ingress-controller:
      controller:
        config:
          externalStatusAddress: api.{{ .Environment.Values.domain }}
  - opensync-mqtt-broker:
      persistence:
        storageClass: "{{ .Environment.Values.storageClass }}"
  - zookeeper:
      persistence:
        storageClass: "{{ .Environment.Values.storageClass }}"
  - kafka:
      persistence:
        storageClass: "{{ .Environment.Values.storageClass }}"
  - cassandra:
      persistence:
        storageClass: "{{ .Environment.Values.storageClass }}"
  - postgresql:
      persistence:
        storageClass: "{{ .Environment.Values.storageClass }}"
