apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: postgresql
      release: tip
  podMetricsEndpoints:
  - port: http-metrics
  namespaceSelector:
    any: true

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-ingress-exporter
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: tip-nginx-ingress-controller
  podMetricsEndpoints:
  - port: prometheus
  namespaceSelector:
    any: true