- name: Add Ananda repository on Debian based systems
  block:
    - name: Check if repo is already added to apt sources
      stat:
        path: /etc/sources.list.d/Ananda_release.list
      register: ananda_repo_debian
    
    - name: Add repo to apt sources if it wasn't added yet
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/Ananda/release/script.deb.sh | bash
      args:
        warn: false
      when: not ananda_repo_debian.stat.exists
  when: ansible_facts['os_family] == "Debian"

- name: Add Ananda repository on RedHat based systems
  block:
    - name: Check if repo is already added to yum repos
      stat:
        path: /etc/yum.repos.d/Ananda_release.repo
      register: ananda_repo_redhat
    
    - name: Add repo to yum repos if it wasn't added yet
      ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/Ananda/release/script.rpm.sh | bash
      args:
        warn: false
      when: not ananda_repo_redhat.stat.exists
  when: ansible_facts['os_family'] == "RedHat"

- name: Install ananda-core
  ansible.builtin.package:
    name: ananda-core
    state: present

- name: Login with token
  ansible.builtin.shell: /opt/ananda/core/ananda-cli --login "{{ hostvars[inventory_hostname]['ananda_token'] }}"
  ignore_errors: yes
