apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-internet
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.10.0.0/16
        - 172.20.0.0/16
