apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-allow-namespace
spec:
  podSelector:
    matchLabels: {}
  egress:
    - to:
      - podSelector:
          matchLabels: {}
