all:
  hosts:
    lab-ctlr:
    lab-ctlr2:
    lab_ctlr3:
    lab-ctlr4:
    lab-ctlr5:
  children:
    ananda_gateways:
      hosts:
        lab-ctlr:
          ansible_host: 10.28.3.100
          ansible_user: lanforge
          ansible_become_pass: "{{ lookup('amazon.aws.aws_secret', 'Testbeds/UserCredentials.lanforge_user_password', nested=true) }}"
          ansible_ssh_pass: "{{ lookup('amazon.aws.aws_secret', 'Testbeds/UserCredentials.lanforge_user_password', nested=true) }}"
          ansible_ssh_common_args: -J ubuntu@3.130.51.163
          ananda_token: "{{ lookup('amazon.aws.aws_secret', 'Ananda/GatewayTokens.lab-ctlr', nested=true) }}"
        lab-ctlr2:
          ansible_host: 10.28.3.101
          ansible_user: lanforge
          ansible_become_pass: "{{ lookup('amazon.aws.aws_secret', 'Testbeds/UserCredentials.lanforge_user_password', nested=true) }}"
          ansible_ssh_pass: "{{ lookup('amazon.aws.aws_secret', 'Testbeds/UserCredentials.lanforge_user_password', nested=true) }}"
          ansible_ssh_common_args: -J ubuntu@3.130.51.163
          ananda_token: "{{ lookup('amazon.aws.aws_secret', 'Ananda/GatewayTokens.lab-ctlr2', nested=true) }}"
        lab-ctlr3:
          ansible_host: 10.28.3.102
          ansible_user: lanforge
          ansible_become_pass: "{{ lookup('amazon.aws.aws_secret', 'Testbeds/UserCredentials.lanforge_user_password', nested=true) }}"
          ansible_ssh_pass: "{{ lookup('amazon.aws.aws_secret', 'Testbeds/UserCredentials.lanforge_user_password', nested=true) }}"
          ansible_ssh_common_args: -J ubuntu@3.130.51.163
          ananda_token: "{{ lookup('amazon.aws.aws_secret', 'Ananda/GatewayTokens.lab-ctlr3', nested=true) }}"
        lab-ctlr4:
          ansible_host: 10.28.3.103
          ansible_user: lanforge
          ansible_become_pass: "{{ lookup('amazon.aws.aws_secret', 'Testbeds/UserCredentials.lanforge_user_password', nested=true) }}"
          ansible_ssh_pass: "{{ lookup('amazon.aws.aws_secret', 'Testbeds/UserCredentials.lanforge_user_password', nested=true) }}"
          ansible_ssh_common_args: -J ubuntu@3.130.51.163
          ananda_token: "{{ lookup('amazon.aws.aws_secret', 'Ananda/GatewayTokens.lab-ctlr4', nested=true) }}"
        lab-ctlr5:
          ansible_host: 10.28.3.104
          ansible_user: lanforge
          ansible_become_pass: "{{ lookup('amazon.aws.aws_secret', 'Testbeds/UserCredentials.lanforge_user_password', nested=true) }}"
          ansible_ssh_pass: "{{ lookup('amazon.aws.aws_secret', 'Testbeds/UserCredentials.lanforge_user_password', nested=true) }}"
          ansible_ssh_common_args: -J ubuntu@3.130.51.163
          ananda_token: "{{ lookup('amazon.aws.aws_secret', 'Ananda/GatewayTokens.lab-ctlr5', nested=true) }}"
