monitoring:
  namespace: monitoring
  domain: example.com

oidc:
  issuerUrl: 'https://telecominfraproject.auth0.com/' # workplace-integration40-dev for development
  clientId: clientId
  clientSecret: clientSecret
  cookieSecret: egh24Y$GB2rh2t # arbitrary random string, not really a secret
