---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-oauth
  namespace: {{ .Values.monitoring.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx-sso
    nginx.ingress.kubernetes.io/custom-http-errors: "500,501,502,503"
  labels:
    k8s-app: oauth2-proxy
spec:
  rules:
  - host: kibana.{{ .Values.monitoring.domain }}
    http:
      paths:
        - path: /oauth2
          backend:
            serviceName: oauth2-proxy
            servicePort: 4180
