---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    k8s-app: oauth2-proxy
spec:
  type: ExternalName
  externalName: oauth2-proxy.{{ .Values.proxy.namespace }}.svc.cluster.local
