apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-exporter
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: mosquitto-exporter
    release: tip
spec:
  selector:
    matchLabels:
      app: mosquitto-exporter
      release: tip
  template:
    metadata:
      labels:
        app: mosquitto-exporter 
        release: tip
    spec:
      containers:
      - args:
        - "--endpoint"
        - "tls://tip-opensync-mqtt-broker.tip.svc.cluster.local:1883"
        - "--bind-address"
        - "0.0.0.0:9234"
        - "--cert"
        - "/certs/mqttservercert.pem"
        - "--key"
        - "/certs/mqttserverkey_dec.pem"
        name: mosquitto-exporter
        image: sapcc/mosquitto-exporter:0.6.0
        ports:
        - name: http-metrics
          containerPort: 9234
        volumeMounts:
        - mountPath: /certs/cacert.pem
          name: opensync-mqtt-broker-truststore
          subPath: cacert.pem
        - mountPath: /certs/mqttservercert.pem
          name: opensync-mqtt-broker-truststore
          subPath: servercert.pem
        - mountPath: /certs/mqttserverkey_dec.pem
          name: opensync-mqtt-broker-truststore
          subPath: serverkey_dec.pem
      volumes:
      - name: opensync-mqtt-broker-truststore
        secret:
          defaultMode: 420
          secretName: opensync-mqtt-broker-certs
