apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-exporter
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app: mosquitto-exporter
    release: tip
spec:
  selector:
    matchLabels:
      app: mosquitto-exporter
      release: tip
  template:
    metadata:
      labels:
        app: mosquitto-exporter 
        release: tip
    spec:
      containers:
      - args:
        - "--endpoint"
        - "tls://{{ .Values.target.service.name }}.{{ .Values.target.namespace }}.svc.cluster.local:{{ .Values.target.service.port }}"
        - "--bind-address"
        - "0.0.0.0:9234"
        - "--cert"
        - "/certs/clientcert.pem"
        - "--key"
        - "/certs/clientkey.pem"
        command:
        - /mosquitto_exporter
        name: mosquitto-exporter
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - name: http-metrics
          containerPort: 9234
        volumeMounts:
        - mountPath: /certs/clientcert.pem
          name: opensync-mqtt-broker-truststore
          subPath: clientcert.pem
        - mountPath: /certs/clientkey.pem
          name: opensync-mqtt-broker-truststore
          subPath: clientkey_dec.pem
      volumes:
      - name: opensync-mqtt-broker-truststore
        secret:
          defaultMode: 420
          secretName: opensync-mqtt-broker-certs
