---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-operator-prometheus-oauth
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    k8s-app: oauth2-proxy
spec:
  rules:
  - host: prometheus.{{ .Values.monitoring.domain }}
    http:
      paths:
        - path: /oauth2
          backend:
            serviceName: oauth2-proxy
            servicePort: 4180
