fullnameOverride: kafka

minBrokerId: 100
resources:
  limits:
    cpu: 1000m
    memory: 800Mi
  requests:
    cpu: 100m
    memory: 800Mi

zookeeper:
  resources:
    limits:
      cpu: 500m
      memory: 400Mi
    requests:
      cpu: 100m
      memory: 400Mi