# Loosely based on https://wiki.alpinelinux.org/wiki/FreeRadius_EAP-TLS_configuration with FreeRADIUS 3 changes in mind
- name: Install freeradius
  apt:
    name: freeradius

- name: Unlink default config
  file:
    path: /etc/freeradius/3.0/sites-enabled/default
    state: absent
  notify: Restart FreeRADIUS

- name: Copy inner-tunnel FreeRADIUS config
  copy:
    src: inner-tunnel.config
    dest: /etc/freeradius/3.0/sites-available/inner-tunnel
  notify: Restart FreeRADIUS

- name: Copy custom FreeRADIUS config
  copy:
    src: site.config
    dest: /etc/freeradius/3.0/sites-available/site
  notify: Restart FreeRADIUS

- name: Copy clients.conf
  copy:
    src: clients.conf
    dest: /etc/freeradius/3.0/clients.conf
  notify: Restart FreeRADIUS

- name: Copy tls config
  copy:
    src: tls
    dest: /etc/freeradius/3.0/sites-available/tls
  notify: Restart FreeRADIUS

- name: Copy EAP mod configuration
  copy:
    src: eap
    dest: /etc/freeradius/3.0/mods-available/eap
  notify: Restart FreeRADIUS

- name: Copy users
  copy:
    src: users
    dest: /etc/freeradius/3.0/mods-config/files/authorize
  notify: Restart FreeRADIUS

- name: Link user file in freeradius dir to the authorize file
  file:
    src: /etc/freeradius/3.0/mods-config/files/authorize
    dest: /etc/freeradius/3.0/users
    state: link
    force: yes

- name: Enable custom FreeRADIUS config
  file:
    src: /etc/freeradius/3.0/sites-available/site
    dest: /etc/freeradius/3.0/sites-enabled/site
    state: link

- name: Make FreeRADIUS certs bootstrap script executable
  file:
    path: /etc/freeradius/3.0/certs/bootstrap
    mode: '0755'

- name: Generate certificates using bootstrap script
  shell: /etc/freeradius/3.0/certs/bootstrap
  args:
    chdir: /etc/freeradius/3.0/certs/
    creates: server.key
  notify: Restart FreeRADIUS

- meta: flush_handlers
