---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: {{ .Values.monitoring.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - env:
        - name: OAUTH2_PROXY_PROVIDER
          value: oidc
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: '*'
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: {{ .Values.oidc.issuerUrl }}
        - name: OAUTH2_PROXY_CLIENT_ID
          value: {{ .Values.oidc.clientId }}
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: {{ .Values.oidc.clientSecret }}
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: {{ .Values.oidc.cookieSecret }}
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: "0.0.0.0:4180"
        - name: OAUTH2_PROXY_COOKIE_SECURE
          value: 'true'
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: IfNotPresent
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
