---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-oauth
  namespace: {{ .Values.monitoring.namespace }}
  annotations:
    meta.helm.sh/release-name: kibana
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kibana
    app.kubernetes.io/managed-by: Helm
    chart: kibana-3.2.6
    heritage: Helm
    release: kibana
spec:
  rules:
  - host: kibana.{{ .Values.monitoring.domain }}
    http:
      paths:
        - path: /oauth2
          backend:
            serviceName: oauth2-proxy
            servicePort: 4180
