grafana:
    slack_api_url: ENC[AES256_GCM,data:zAswmtSiM9HenATnqKKenxlTxSatSOUL9q5As5zpTgEcmlNnZf8yVRqCBw0Y3QVyOm1EmkO0bkqTclcuOPC7rXnqzLxAhBkM6wR5v0qDbt3W,iv:BOFaXDOi3bivQBTx1g66ZvdXlURSMeYC72RAEYZwpkc=,tag:Z38Y/a1fsSVDyQD3sfth1w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:289708231103:alias/helm-secrets
          created_at: "2022-07-11T12:54:50Z"
          enc: AQICAHiG/4CitJjM31GdYxTw9OLz/Zs5oK+DCq0cU2fAjtAA3AGgr/yv8vhzDeiU/2AFGjmCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwcY1HiP4LXObPBjqAgEQgDuP3Ar1XM3tsXDjZnJ+VwwC3aufnq6lw1FYUxwObrJfWXMziok8tPwsUa3cEPoE6Z2rKBO89rA5lT0h9w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-11T12:54:51Z"
    mac: ENC[AES256_GCM,data:cvFfZjqfHWcgDq9ocEcjrqM0gdv34Cn+RXYI5iA2o7DlRnD2GWNqb4d78cf5uJeQirAyiHqtJiqGsphUNf78AQf9vofChHutBSshgm5F3CctNEJeXsQQBgRMlAI06EclzYWz8wDWa+HWHOvCX3MsM7jMJDKu4H+/UMzxibl2XqQ=,iv:bdRdjmGyPH1x9UKRYAPHuuh2SaZkfuIRfhbgtcYwpfA=,tag:H3JzFqkdWubvelcbvOj+Eg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
