replicaCount: 1
image:
  repository: us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler
  tag: v1.16.5
autoDiscovery:
  clusterName: {{ .Environment.Values.clusterName }}
awsRegion: {{ .Environment.Values.awsRegion }}
rbac:
  create: true
  pspEnabled: true
  serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Environment.Values.awsAccountID }}:role/cluster_autoscaler

