#!/bin/bash

. ./utils.sh

check_env
echo "Scaling cluster:"
show_env
echo "Press ENTER to continue [or CTRL-C to exit]"
read -r

logv startscale "$(date)"
echo "Determine caller identity"
if [ -n "$AWS_PROFILE" ] ; then
    account_id=$(aws sts get-caller-identity --query Account --output text --profile "$AWS_PROFILE")
else
    account_id=$(aws sts get-caller-identity --query Account --output text)
fi
logv accountid "$account_id"
if [ -z "$account_id" ] ; then
    echo "Unable to determine caller-identity!"
    exit 1
fi

config_file="cluster.$CLUSTER_NAME.yaml"
echo "Generating cluster.tpl.yml file -> $config_file"
envsubst < cluster.tpl.yaml > "$config_file"

#eksctl create nodegroup -f cluster.$CLUSTER_NAME.yaml
eksctl scale nodegroup -f "cluster.$CLUSTER_NAME.yaml"
logv scaled "$CLUSTER_NAME"
logv endscale "$(date)"
