{
 "title": "TIP Cloud Controller Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(com_netflix_servo_singledatasource_numberofactivejdbcconnections_value, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number Of Active JDBC Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_netflix_servo_singledatasource_numberofactivejdbcconnections_value{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Idle JDBC Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_netflix_servo_singledatasource_numberofidlejdbcconnections_value{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Get JDBC Connection Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(com_netflix_servo_jdbc_getconnection_value{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cassandra Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(com_netflix_servo_cassandra_execute_value{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cassandra Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(com_netflix_servo_cassandra_execute_errors_value{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka System Events Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(com_netflix_servo_kafka_producer_events_msg_written_value{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka System Events Write Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(com_netflix_servo_kafka_producer_events_msg_errors_value{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka service metrics writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(com_netflix_servo_kafka_producer_wlan_metrics_msg_written_value{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kafka service metrics write errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(com_netflix_servo_kafka_producer_wlan_metrics_msg_errors_value{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OVSDB Tasks In Flight",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "com_netflix_servo_osgw_ovsdb_tasksinflight_value{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OVSDB Rejected Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(com_netflix_servo_osgw_ovsdb_rejectedtasks_value{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OVSDB Transact Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(com_netflix_servo_osgw_ovsdb_transact_value{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MQTT Messages received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "cpm" }
   ],
   "targets": [
    {
     "expr": "rate(com_netflix_servo_osgw_mqtt_messagesreceived_value{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}