{
 "title": "JVM metrics per Pod",
 "description": "Complete dashboard using metrics from Prometheus JMX exporter, with drill down per namespace > pod",
 "tags": [ "JVM" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jvm_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(jvm_info{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{namespace=\"$namespace\", pod=\"$pod\"}, pool)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{namespace=\"$namespace\", pod=\"$pod\"}, area)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\",pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{namespace=\"$namespace\",pod=\"$pod\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Available CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "os_available_processors{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_system_load_average{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "os_open_file_descriptor_count{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "os_system_cpu_load{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "System"
    },
    {
     "expr": "os_process_cpu_load{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JVM"
    }
   ]
  },
  {
   "title": "Memory area [$memarea]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"$memarea\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",pod=\"$pod\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "repeat": "mempool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=~\"$mempool\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=~\"$mempool\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=~\"$mempool\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\",pod=~\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",pod=~\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 161 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Physical memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "os_total_physical_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Total physical memory"
    },
    {
     "expr": "os_committed_virtual_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Committed virtual memory"
    },
    {
     "expr": "os_free_physical_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "Free physical memory"
    }
   ]
  }
 ]
}