{
 "title": "Pod Events",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_container_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of waiting pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{namespace=~\"$namespace\", reason!=\"ContainerCreating\"}) by (namespace) + sum(kube_pod_init_container_status_waiting_reason{namespace=~\"$namespace\", reason!=\"ContainerCreating\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Pod restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[1m])) by (namespace) + sum(changes(kube_pod_init_container_status_restarts_total{namespace=~\"$namespace\"}[1m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{namespace=~\"$namespace\", reason!=\"ContainerCreating\"}) by (namespace, pod, reason) > 0"
    }
   ]
  }
 ]
}