# This is a development override file.
# It overrides the default Tip-Wlan parent chart behaviour
#
# It can be tweaked, based on the need to support different
# dev environments.
# This file expects to have a GlusterFS storage solution running
# before "helm install" is performed. 
#################################################################
# Global configuration overrides.
#
# These overrides will affect all helm charts (ie. applications)
# that are listed below and are 'enabled'.
#################################################################
global:
  # Change to an unused port prefix range to prevent port conflicts
  # with other instances running within the same k8s cluster
  nodePortPrefix: 302
  nsPrefix: tip
  # image pull policy
  pullPolicy: Always

  repository: tip-tip-wlan-cloud-docker-repo.jfrog.io
  # override default mount path root directory
  # referenced by persistent volumes and log files
  persistence:

  # flag to enable debugging - application support required
  debugEnabled: true

# Annotations for namespace
annotations: {
    "helm.sh/resource-policy": keep
}

createReleaseNamespace: false

# Docker registry secret
dockerRegistrySecret: eyJhdXRocyI6eyJ0aXAtdGlwLXdsYW4tY2xvdWQtZG9ja2VyLXJlcG8uamZyb2cuaW8iOnsidXNlcm5hbWUiOiJnbGViIiwicGFzc3dvcmQiOiJAM3g1N1hRbWtLVkdGdDhVam55ZiIsImVtYWlsIjoiZ2xlYkBvcHNmbGVldC5jb20iLCJhdXRoIjoiWjJ4bFlqcEFNM2cxTjFoUmJXdExWa2RHZERoVmFtNTVaZz09In19fQ==
#################################################################
# Enable/disable and configure helm charts (ie. applications)
# to customize the TIP-WLAN deployment.
#################################################################
opensync-gw-static:
  enabled: true
opensync-mqtt-broker:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "default"
wlan-cloud-graphql-gw:
  enabled: true
  env:
    portalsvc: graphql.tip.4c74356b41.com
  ingress:
    enabled: true
    hosts:
    - host: graphql.tip.4c74356b41.com
      paths:
      - "/"
wlan-cloud-static-portal:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - host: portal.tip.4c74356b41.com
      paths:
      - "/"
wlan-portal-service:
  enabled: true
wlan-prov-service:
  enabled: true
wlan-ssc-service:
  enabled: true
nginx-ingress-controller:
  enabled: true
  controller:
    metrics:
      enabled: true
    config:
      externalStatusAddress: "api.tip.4c74356b41.com"
zookeeper:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "default"
kafka:
  enabled: true
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "default"
cassandra:
  enabled: true
  config:
## NOTE: If we are using glusterfs as Storage class, we don't really need 
## replication turned on, since the data is anyway replicated on glusterfs nodes
## Replication is useful when we use HostPath as storage mechanism
## For Hostpath storage, recommendation is cluster_size: 3 and seed_size: 2
    cluster_size: 1
    seed_size: 1
  persistence:
    enabled: true
    storageClass: "default"
postgresql:
  enabled: true
## NOTE: If we are using glusterfs as Storage class, we don't really need 
## replication turned on, since the data is anyway replicated on glusterfs nodes
## Replication is useful: 
## a. When we use HostPath as storage mechanism
## b. If master goes down and one of the slave is promoted as master
  replication:
    enabled: false
    slaveReplicas: 1
  persistence:
    enabled: true
    storageClass: "default"