name: Helmfile validation and deployment

on:
  push:
    paths:
      - 'helmfile/cloud-sdk/**'
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  helmfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install helmfile
        run: |
          sudo wget https://github.com/roboll/helmfile/releases/download/v0.139.7/helmfile_linux_amd64 -O /usr/local/bin/helmfile
          sudo chmod +x /usr/local/bin/helmfile
      - name: install sops
        run: |
          sudo wget https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux -O /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops
      - name: install Helm plugins
        run: |
          helm plugin install https://github.com/jkroepke/helm-secrets --version v3.7.0
          helm plugin install https://github.com/databus23/helm-diff --version v3.1.3
      - name: connect to EKS ${{ env.AWS_EKS_NAME }}
        run: aws eks update-kubeconfig --name ${{ env.AWS_EKS_NAME }}
        env:
          AWS_EKS_NAME: tip-wlan-main                                                                                                                                                                                                    
          AWS_DEFAULT_REGION: us-east-2                         
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}        
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: helmfile diff
        if: github.event_name == 'pull_request'
        working-directory: helmfile/cloud-sdk
        run: helmfile -e amazon-cicd diff
        env:
          AWS_DEFAULT_REGION: us-east-2                         
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}        
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
      - name: helmfile apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        working-directory: helmfile/cloud-sdk
        run: helmfile -e amazon-cicd apply
        env:
          AWS_DEFAULT_REGION: us-east-2
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
